### ISSUE TITLE
MemoryPath.getName(int i) should return a single element

### ISSUE THREAD

**Issue by miraculix0815** [SylvainJuge/memoryfs#4]
Hello sylvain,

MemoryPath.getName(int i) returns something like subpath(0, i) at the moment.

According to the behaviour of the standard FS it should return something like
new MemoryPath(fs, parts, index, index + 1, absolute && index == 0);

Please change the behaviour so that only a single element will be returned.

Thanks in advance,
Jan

**Comment by SylvainJuge** [comment]
Hi Jan,

Thanks for your feedback, and current implementation is clearly not consistent with default FS.

getName(int i) must return a (relative) path with a path with a single element.
