### ISSUE TITLE
MemoryPath.relativize() on "/" fails

### ISSUE THREAD

**Issue by miraculix0815** [SylvainJuge/memoryfs#5]
Hello Sylvain,

pleas add the following test to the set for relativize
  checkRelativize("/", "/a/b", "a/b")

i propose to implement it with
  relativePath.addAll(path.parts.subList(i, path.parts.size()));
in replacement for
  relativePath.addAll(path.parts.subList(i, parts.size()));

**Comment by SylvainJuge** [comment]
Ooops, that's clearly a bug, probably a typo and it almost worked by coincidence.
